### ISSUE TITLE
NPE when slot email is null in UserProfile

### ISSUE THREAD

**Issue by Luis-Cruz** [FenixEdu/messaging#52]
`java.lang.Error: java.lang.NullPointerException
	at pt.ist.dot.scripts.HackMessagingSystem.runTask(HackMessagingSystem.java:24)
	at org.fenixedu.bennu.scheduler.CronTask$1.call(CronTask.java:79)
	at org.fenixedu.bennu.scheduler.CronTask$1.call(CronTask.java:75)
	at pt.ist.fenixframework.backend.jvstmojb.JvstmOJBTransactionManager.handleWriteCommand(JvstmOJBTransactionManager.java:209)
	at pt.ist.fenixframework.backend.jvstmojb.JvstmOJBTransactionManager.withTransaction(JvstmOJBTransactionManager.java:146)
	at org.fenixedu.bennu.scheduler.CronTask.innerAtomicRun(CronTask.java:75)
	at org.fenixedu.bennu.scheduler.CronTask.run(CronTask.java:54)
	at org.fenixedu.bennu.scheduler.custom.ClassBean$Executer.runTask(ClassBean.java:287)
	at org.fenixedu.bennu.scheduler.custom.ClassBean$Executer.runCompileAndExecute(ClassBean.java:302)
	at org.fenixedu.bennu.scheduler.custom.ClassBean$Executer.run(ClassBean.java:293)
Caused by: java.lang.NullPointerException
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:673)
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:633)
	at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:111)
	at org.fenixedu.messaging.core.domain.MessagingSystem$Util.isValidEmail(MessagingSystem.java:125)
	at org.fenixedu.messaging.emaildispatch.domain.LocalEmailMessageDispatchReport.lambda$dispatch$0(LocalEmailMessageDispatchReport.java:83)
	at org.fenixedu.messaging.emaildispatch.domain.LocalEmailMessageDispatchReport.lambda$emailsByMessageLocale$4(LocalEmailMessageDispatchReport.java:136)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.fenixedu.messaging.emaildispatch.domain.LocalEmailMessageDispatchReport.emailsByMessageLocale(LocalEmailMessageDispatchReport.java:136)
	at org.fenixedu.messaging.emaildispatch.domain.LocalEmailMessageDispatchReport.dispatch(LocalEmailMessageDispatchReport.java:117)
	at org.fenixedu.messaging.emaildispatch.EmailDispatcherContextListener$LocalEmailMessageDispatcher.dispatch(EmailDispatcherContextListener.java:18)
	at org.fenixedu.messaging.core.domain.MessagingSystem.advised$dispatch(MessagingSystem.java:92)
	at org.fenixedu.messaging.core.domain.MessagingSystem$callable$dispatch.call(Advice Library Automatically Generated Class)
	at pt.ist.fenixframework.backend.jvstmojb.JvstmOJBTransactionManager.handleWriteCommand(JvstmOJBTransactionManager.java:179)
	at pt.ist.fenixframework.backend.jvstmojb.JvstmOJBTransactionManager.withTransaction(JvstmOJBTransactionManager.java:146)
	at pt.ist.fenixframework.atomic.AtomicContext.perform(AtomicContext.java:30)
	at org.fenixedu.messaging.core.domain.MessagingSystem.dispatch(MessagingSystem.java)
	at pt.ist.dot.scripts.HackMessagingSystem.runTask(HackMessagingSystem.java:16)
	... 9 more`

**Comment by Luis-Cruz** [comment]
Fixed by commit: 8bd8be4fdd6f5b9326a5f8e0a333e9b6a2ac1a14
