### ISSUE TITLE
EmailBlacklist not properly initialized causes NPE

### ISSUE THREAD

**Issue by Luis-Cruz** [FenixEdu/messaging#9]
The following exception happens:

java.lang.NullPointerException
	at org.fenixedu.messaging.emaildispatch.domain.EmailBlacklist.getBlacklist(EmailBlacklist.java:48)
	at org.fenixedu.messaging.emaildispatch.domain.EmailBlacklist.log(EmailBlacklist.java:97)

because when the EmailBlacklist is created it is not properly initialized.

**Comment by Luis-Cruz** [comment]
Setting the blacklist slot with an empty json array on construction may solve this.
